### ISSUE TITLE
Latest version of Postscribe Occassionaly display JS code instead of evaluting it

### ISSUE THREAD

**Issue by sajalaspl** [krux/postscribe#172]
Hi @sethyates and @jnewman,

Sorry, I was not able to produce a jsfiddle for this, but I would be as descriptive as I could be. I've tried the latest version, and I found that couple of my ads were not rendering, instead inline JS code was displayed as shown following.

![postscribe](https://cloud.githubusercontent.com/assets/3337683/14808733/65e1b222-0ba5-11e6-9aed-d2d01d5f38f1.png)

As you could see, on the right side of logo, it displays the JS code instead of evaluating it as a JS code. The reason behind that, as shown in the firebug, is the code is injected just outside of "script" tag. So, we've blank "script" tag and the code sits after that, so it won't be parsed as JS.

In case if it helps you, here's my ad code I'm using.
```

<script>
postscribe("#ad10", '<script src="http://eas3.emediate.se/eas?cu=8272;cre=mu;js=y;pageviewid=;target=_blank" type="text/javascript"><\/script>');
</script>
```

**Comment by sethyates** [comment]
Is that using the latest version of postscribe from an `npm build`?  There was a bug in the html parser in an earlier version that would sometimes do that but I thought that was fixed in a more recent version.

**Comment by sajalaspl** [comment]
Yes, @sethyates I'm using this one.

https://raw.githubusercontent.com/sajalsoni/testing_sks/master/postscribe.js

**Comment by jnewman** [comment]
Confirmed this is broken in latest and works in an older version. Looking into a fix. Can repro in a unit test like:

```
// in remote-file.js

// Hello
document.write('<script>');
document.write("'Oh, no!'");
document.write('<\/script>');
```

```
// In write-comparisons

'only:wlma: writes code inside tag': '<script src="remote/multi-write-script.js" type="text/javascript"><\/script>'
```

**Comment by jnewman** [comment]
The issue is caused by a difference in behavior in prescribe. Calling readToken w/ a startTag previously would return `null`, now it returns the start token, which is then autoclosed by postscribe. Investigating a fix.

**Comment by sajalaspl** [comment]
Hi @sethyates, I think it's not fixed yet as I've just tested the 2.0.5 version (cloud link) and still couple of (not all) my ads produce inline JS code. Following are the specific ads that produce inline JS code.

postscribe('#ad5', '<script src="http://eas3.emediate.se/eas?cu=5831;cre=mu;js=y;pageviewid=;target=_blank" type="text/javascript"><\/script>');

postscribe('#ad9', '<script src="http://eas3.emediate.se/eas?cu=6073;cre=mu;js=y;pageviewid=;target=_blank" type="text/javascript"><\/script>');

**Comment by sethyates** [comment]
The fix was in 2.0.6. Please retest with that version.

**Comment by sajalaspl** [comment]
Thanks @sethyates, just in case you would like to fix cloud link point out to 2.0.6 instead of 2.0.5!

**Comment by sethyates** [comment]
Thanks. I've updated that link.
